# -*- coding: utf-8 -*-
"""INNO-2241.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NneHH-Ob6K8WHC329NNsru5YqIX7f1ev
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset1 = pd.read_csv('/content/OTT Final Cleaned data.csv')

dataset1

del dataset1['Unnamed: 0']

X = dataset1.iloc[:,1:6].values
y = dataset1.iloc[:,6].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=2)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

y_pred=clf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))